#!/usr/bin/env python3

from base64 import b64encode

input_string = "49276d206b696c6c696e6720796f757220627261696e206c696b65206120706f69736f6e6f7573206d757368726f6f6d"

input_bytes = bytes.fromhex(input_string)

output_bytes = b64encode(input_bytes)

output_string = str(object=output_bytes, encoding='utf-8')

output_message = """SET 01 PROBLEM 01: Convert hex to base64 and back
Hex input:        {}
Output in Base64: {}"""

print(output_message.format(input_string, output_string))
