#!/usr/bin/env python3

from base64 import b64decode
from libpals.util import xor_repeatedkey, xor_find_multichar_key

ciphertext = b64decode(open('data/6.txt', 'r').read())

key_bytes = xor_find_multichar_key(ciphertext)

key_string = str(object=key_bytes, encoding='utf-8')

plaintext_bytes = xor_repeatedkey(ciphertext, key_bytes)

plaintext_excerpt = str(object=plaintext_bytes[:242], encoding='utf-8')

output_message = """SET 01 PROBLEM 06: Break repeating-key XOR
Key: {}

Plaintext (first 242 bytes):

{}"""

print(output_message.format(key_string, plaintext_excerpt))
