#!/usr/bin/env python3

# Copyright 2016 Carl Winbäck. See the COPYING file at the top-level directory
# of this distribution.

from libpals.util import IrregularOracle, IrregularOracleCracker

oracle = IrregularOracle()
cracker = IrregularOracleCracker(oracle)

output_message = """SET 02 CHALLENGE 14: Byte-at-a-time ECB decryption (Harder)

Plaintext:
"""

print(output_message)
print(cracker.crack().decode(encoding='ascii'))
