#!/usr/bin/env python3

# Copyright 2014 Carl Winbäck. See the COPYING file at the top-level directory
# of this distribution.

from libpals.util import xor_singlechar, xor_find_singlechar_key

input_string = '1b37373331363f78151b7f2b783431333d78397828372d363c78373e783a393b3736'

ciphertext = bytes.fromhex(input_string)

result = xor_find_singlechar_key(ciphertext)

plaintext = result['plaintext']

output_message = """SET 01 PROBLEM 03: Single-character XOR Cipher
Input: {}
Key:
  Decimal: {}
  Hex: {}
  ASCII: {}
Message: {}"""

print(output_message.format(input_string,
                            result['key'],
                            hex(result['key']),
                            chr(result['key']),
                            str(object=plaintext, encoding='ascii')))
