#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from base64 import b64decode
from Crypto.Cipher import AES

cipher = AES.new(b'YELLOW SUBMARINE', AES.MODE_ECB)

ciphertext = b64decode(open('data/7.txt', 'r').read())

plaintext = cipher.decrypt(ciphertext)

output_message = """SET 01 PROBLEM 07: AES in ECB Mode

Plaintext (first 242 bytes):

{}"""

print(output_message.format(plaintext[:242].decode("ascii")))
