#!/usr/bin/env python3

# Copyright 2016 Carl Winbäck. See the COPYING file at the top-level directory
# of this distribution.

from libpals.util import ecb_or_cbc, StaticOracle, StaticOracleCracker

oracle = StaticOracle()
cracker = StaticOracleCracker(oracle)
mode = ecb_or_cbc(oracle.encrypt(b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'))

output_message = """SET 02 CHALLENGE 12: Byte-at-a-time ECB decryption (Simple)

Mode: {}

Plaintext:

{}"""

print(output_message.format(mode.upper(),
                            cracker.crack().decode(encoding='ascii')))
