#!/usr/bin/env python3

from operator import itemgetter
from libpals.util import xor_singlechar, xor_find_singlechar_key

input_string = '1b37373331363f78151b7f2b783431333d78397828372d363c78373e783a393b3736'

ciphertext = bytes.fromhex(input_string)

key = xor_find_singlechar_key(ciphertext)['key']

plaintext = xor_singlechar(ciphertext, key)

output_message = """SET 01 PROBLEM 03: Single-character XOR Cipher
Input: {}
Key:
  Decimal: {}
  Hex: {}
  ASCII: {}
Message: {}"""

print(output_message.format(input_string,
                            key,
                            hex(key),
                            chr(key),
                            str(object=plaintext, encoding='ascii')))
