#!/usr/bin/env python3

# Copyright 2014 Carl Winbäck. See the COPYING file at the top-level directory
# of this distribution.

from base64 import b64decode
from libpals.util import (
    divide,
    fixed_xor,
    aes_128_cbc_decrypt,
    aes_128_cbc_encrypt
)

key = b'YELLOW SUBMARINE'

iv = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

ciphertext = b64decode(open('data/10.txt', 'r').read())

plaintext= aes_128_cbc_decrypt(key, iv, ciphertext)

output_message = """SET 02 PROBLEM 10: Implement CBC mode

Plaintext (first 242 bytes):

{}"""

print(output_message.format(plaintext[:242].decode("ascii")))
