#!/usr/bin/env python3

# Copyright 2014 Carl Winbäck. See the COPYING file at the top-level directory
# of this distribution.

# This is just a simple example of the pkcs7pad_remove function. See
# tests/main_test.py for real unit tests.

from libpals.util import pkcs7pad_remove

input_bytes = b'ICE ICE BABY\x04\x04\x04\x04'
result_bytes = pkcs7pad_remove(input_bytes)

output_message = """SET 02 PROBLEM 15: PKCS#7 padding validation

Input: {}
Result: {}"""

print(output_message.format(input_bytes,
                            result_bytes.decode('ascii')))
