#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from base64 import b64decode
from Crypto.Cipher import AES

cipher = AES.new('YELLOW SUBMARINE', AES.MODE_ECB)

data_file = open('../data/gist_3132853.txt', encoding='ascii')

ciphertext = b64decode(data_file.read())

plaintext = cipher.decrypt(ciphertext)

output_message = """SET 01 PROBLEM 07: AES in ECB Mode

Plaintext (first 242 bytes):

{}"""

print(output_message.format(plaintext[:242].decode("ascii")))
