#!/usr/bin/env python3

from operator import itemgetter

character_frequency = {
    'e': 27,
    't': 26,
    'a': 25,
    'o': 24,
    'i': 23,
    'n': 22,
    's': 21,
    'r': 20,
    'h': 19,
    'l': 18,
    'd': 17,
    'c': 16,
    'u': 15,
    'm': 14,
    'f': 13,
    'p': 12,
    'g': 11,
    'w': 10,
    'y': 9,
    'b': 8,
    'v': 7,
    'k': 6,
    'x': 5,
    ' ': 4,
    'j': 3,
    'q': 2,
    'z': 1
}


def xor_singlechar(input_bytes, key_value):
    output = b''

    for char in input_bytes:
        output += bytes([char ^ key_value])

    return output


def xor_find_singlechar_key(ciphertext):
    candidates = list()

    for key_candidate in range(256):
        total_score = 0
        decoded_input = xor_singlechar(ciphertext, key_candidate)

        for byte in decoded_input:
            char_score = character_frequency.get(chr(byte), 0)
            total_score += char_score
        candidates.append((key_candidate, total_score))

    return max(candidates, key=itemgetter(1))


input_string = '1b37373331363f78151b7f2b783431333d78397828372d363c78373e783a393b3736'

ciphertext = bytes.fromhex(input_string)

key = xor_find_singlechar_key(ciphertext)[0]

plaintext = xor_singlechar(ciphertext, key)

output_message = """SET 01 PROBLEM 03: Single-character XOR Cipher
Input: {}
Key:
  Decimal: {}
  Hex: {}
  ASCII: {}
Message: {}"""

print(output_message.format(input_string,
                            key,
                            hex(key),
                            chr(key),
                            str(object=plaintext, encoding='ascii')))
